language: node_js
node_js:
  - "4.0"
  - "6.0"
before_script:
  - npm install -g npm@latest-2
  - npm --version
install:
  - travis_retry npm install
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bc55bc8de370883f25c5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
