language: node_js
node_js:
  - "4.0"
  - "6.0"
sudo: true
before_install:
  - npm install -g npm
  - npm install -g gulp-cli
  - npm install n
  - sudo ./node_modules/.bin/n stable
install:
  - gulp nw
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
