language: node_js
node_js:
  - "4.0"
  - "6.0"
sudo: true
before_install:
  - npm install n
  - sudo ./node_modules/.bin/n stable
  - rm -rf ~/.nvm
  - https://github.com/xtuple/nvm
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
